# Generated by Django 4.0.4 on 2023-09-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_uploadedfileh_delete_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFileh',
            new_name='UploadedFile',
        ),
    ]
