# Generated by Django 4.0.4 on 2023-09-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0003_rename_uploadedfileh_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadedFileh',
        ),
    ]
