# Generated by Django 4.0.4 on 2023-09-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_rename_uploadedfile_uploadedfileh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFileh',
            new_name='UploadedFile',
        ),
    ]
